#!/usr/bin/env bash
set -e

#!/bin/bash
### Mosek
# curl -L http://download.mosek.com/stable/8.1.0.31/mosektoolslinux64x86.tar.bz2 | tar xj
# echo 'Downloaded Mosek'

### CVX (Download only)
# We call cvx_setup in MATLAB to complete the setup
curl -sL http://web.cvxr.com/cvx/cvx-a64.tar.gz | tar zx
echo 'Downloaded CVX'
   
### SReachTools (Download only)
# Call srtinit in MATLAB to complete the setup
## OPTION 1: Fetch a tagged release
SREACHTOOLS_RELEASE=1.3.1
curl -sL https://github.com/sreachtools/SReachTools/archive/v$SREACHTOOLS_RELEASE.zip --output SReachTools.zip
unzip -qq SReachTools.zip
mv SReachTools-$SREACHTOOLS_RELEASE SReachTools
rm SReachTools.zip
echo 'Downloaded SReachTools (Version ' $SREACHTOOLS_RELEASE ')'

# ## OPTION 2: Fetch bleeding edge
# curl -sL https://github.com/sreachtools/SReachTools/archive/master.zip --output SReachTools.zip
# unzip -qq SReachTools.zip
# mv SReachTools-master SReachTools
# rm SReachTools.zip
# echo 'Downloaded SReachTools (bleeding edge)'
   
### Setup MATLAB env for GeoCalcLib, YALMIP, CVX, MPT3, and SReachTools
# Trailing \ implies newline in bash. MATLAB executes the commands in the quotes.
# Make sure each line ends with ;\ to avoid MATLAB throwing errors
# Use GPLK instead of LCP to avoid wierd shifting | Don't do mpt_init again
# 1. Setup CVX
# 2. Fetch and install MPT3 using tbxmanager; Initialize MPT3
# 3. Setup SReachTools
# Even though we do not recommend using savepath, we have to do it here due to
# CodeOcean's setup
matlab -nodisplay -r "\
cd('/cvx');\
cvx_setup();\
fprintf('Installed CVX (Standard bundle)\n\n');\
mkdir('/tbxmanager');\
cd('/tbxmanager');\
urlwrite('http://www.tbxmanager.com/tbxmanager.m', 'tbxmanager.m');\
a=evalc('tbxmanager');\
fprintf('Installed tbxmanager for MPT3\n\n');\
tbxmanager install mpt mptdoc cddmex fourier glpkmex hysdel lcp sedumi espresso;\
mpt_init;\
a=mptopt('lpsolver','glpk','qpsolver','quadprog');\
fprintf('Installed MPT3\n\n');\
cd('/SReachTools');\
srtinit;\
fprintf('Installed SReachTools\n\n');\
savepath;"
# Add Mosek
# addpath('/mosek/8/toolbox/r2014a');\
# fprintf('Installed Mosek\n\n');\
